# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "linkedin"
name = "LinkedIn"
weight = -30
url = "https://linkedin.com/in/gabrielelee"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "github"
name = "GitHub"
weight = -20
url = "https://github.com/kiblitz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gmail"
name = "Gmail"
weight = -10
url = "mailto:g.lee13770334@gmail.com"

[social.params]
icon = "brand-gmail"
